import {SetMap} from '../structs'
import {bindCallback} from '../utils'
import {DependencyMap} from './helpers/dependency-map'


// This file was exported as `DependencyTracker` before,
// but it's apis are used frequently by Lupos Compiler,
// so finally it export all members directly.


/** Caches `Dependency <=> Callback`. */
const DepMap: DependencyMap = new DependencyMap()

/** Mark the latest version of objects which are tracking elements. */
const ElementsDepVersionMap: WeakMap<object, number> = new WeakMap()

/** Tracker stack list. */
const trackerStack: DependencyTracker[] = []

/** Current callback and dependencies that is doing capturing. */
let currentTracker: DependencyTracker | null = null


/** 
 * Execute `fn`, and captures all dependencies during execution,
 * Will execute `fn` in a `try{...}` statement.
 * If any dependent object get changed, calls callback.
 * 
 * Note for tracking same content, `callback` should keep consistent,
 * or it would cant replace old tracking.
 */
export function trackExecution(fn: () => void, callback: Function, scope: object | null = null) {
	beginTrack(callback, scope)

	try {
		fn()
	}
	catch (err) {
		console.error(err)
	}
	finally {
		endTrack()
	}
}


/** 
 * Begin to capture dependencies.
 * Would suggest executing the codes following in a `try{...}` statement.
 * Please note, `callback` get called when any property of tracking object get changed,
 * not only the accurate property that we are tracking by `props` of
 * `trackGet(o, props)` and `trackSet(o, props)`.
 * 
 * If wanting detailed tracking, please use tracker object returned to do snapshot comparing.
 */
export function beginTrack(callback: Function, scope: object | null = null): DependencyTracker {
	let boundCallback = bindCallback(callback, scope)

	if (currentTracker) {
		trackerStack.push(currentTracker)
	}

	return currentTracker = new DependencyTracker(boundCallback)
}


/** 
 * End capturing dependencies.
 * You must ensure to end each capture, or fatal error will happen.
 */
export function endTrack() {
	currentTracker!.apply()

	if (trackerStack.length > 0) {
		currentTracker = trackerStack.pop()!
	}
	else {
		currentTracker = null
	}
}


/** 
 * When doing property getting, add a dependency.
 * Note if a property is not empty, you must ensure it's property key of `obj`.
 */
export function trackGet(obj: object, ...props: PropertyKey[]) {
	if (currentTracker) {
		currentTracker.dependencies.addSeveral(obj, props)
	}
}


/** 
 * When need to visit all properties and descendant properties recursively,
 * e.g., `JSON.stringify(...)`.
 * Note you this api can't be generated by compiler, you must use it manually.
 */
export function trackGetDeeply(obj: object, maxDepth = 10) {
	if (maxDepth === 0) {
		return
	}

	// Array.
	if (Array.isArray(obj)) {
		trackGet(obj, '')

		for (let item of obj) {
			if (item && typeof item === 'object') {
				trackGetDeeply(item, maxDepth - 1)
			}
		}
	}

	// Plain object.
	else {
		trackGet(obj, '')
		
		for (let key of Object.keys(obj)) {
			let item = (obj as any)[key]
			if (item && typeof item === 'object') {
				trackGetDeeply(item, maxDepth - 1)
			}
		}
	}
}


/** When doing setting property, notify the dependency is changed. */
export function trackSet(obj: object, ...props: PropertyKey[]) {
	for (let prop of props) {
		if (prop === '') {
			let callbacks = DepMap.getAllPropCallbacks(obj)
			if (callbacks) {
				for (let callback of callbacks) {
					callback()
				}
			}
		}
		else {
			let callbacks = DepMap.getCallbacks(obj, prop)
			if (callbacks) {
				for (let callback of callbacks) {
					callback()
				}
			}
		}	
	}

	// Should also calls elements callbacks, low frequency.
	if (!props.includes('')) {
		let elementsCallbacks = DepMap.getCallbacks(obj, '')
		if (elementsCallbacks) {
			for (let callback of elementsCallbacks) {
				callback()
			}
		}
	}

	// Upgrade elements dependency version if it exists, for snapshot comparing.
	let version = ElementsDepVersionMap.get(obj)
	if (version !== undefined) {
		ElementsDepVersionMap.set(obj, version + 1)
	}
}


/** Remove all dependencies of a refresh callback. */
export function untrack(callback: Function, scope: object | null = null) {
	let boundCallback = bindCallback(callback, scope)
	DepMap.deleteCallback(boundCallback)
}


/** 
 * Contains captured dependencies, and the refresh callback it need to call after any dependency get changed.
 * Can also use it to compute a dependency values snapshot, and to compare it later.
 */
export class DependencyTracker {

	// Refresh callback, to call it after any dependency changed.
	readonly callback: Function

	// Each object and accessed property.
	readonly dependencies: SetMap<object, PropertyKey> = new SetMap()

	constructor(callback: Function) {
		this.callback = callback
	}

	/** Apply or restore current tracking to global tracking. */
	apply() {
		DepMap.apply(this.callback, this.dependencies)
	}

	/** Remove current tracking from global tracking.  */
	remove() {
		DepMap.deleteCallback(this.callback)
	}

	/** 
	 * Compute current dependency values as a snapshot for comparing them later.
	 * Remember don't use this too frequently,
	 * it will get values by dynamic properties and affect performance.
	 */
	makeSnapshot(): any[] {
		let values: any[] = []

		for (let [dep, prop] of this.dependencies.flatEntries()) {
			if (prop === '') {
				let version = ElementsDepVersionMap.get(dep)
				if (version === undefined) {
					ElementsDepVersionMap.set(dep, version = 0)
				}
				values.push(version)
			}
			else {
				values.push((dep as any)[prop])
			}
		}

		return values
	}

	/** Compare whether dependency values have changed from a previously computed snapshot. */
	compareSnapshot(oldValues: any[]): boolean {
		let index = 0

		// Important notes:
		// We assume each value in old values are always
		// have the same position with new values.
		// This is because haven't doing new tracking.

		for (let [dep, prop] of this.dependencies.flatEntries()) {
			let oldValue = oldValues[index]
			if (prop === '') {
				let newVersion = ElementsDepVersionMap.get(dep)
				if (newVersion !== oldValue) {
					return true
				}
			}
			else {
				let newValue = (dep as any)[prop]
				if (newValue !== oldValue) {
					return true
				}
			}

			index++
		}

		return false
	}
}
